"""Carrier portal — the carrier-facing app surface (v1: mobile web).

Auth model: a durable per-carrier link token generated by the broker
(hash-only storage, revocable by regenerating/deleting). Every endpoint is
scoped to that ONE carrier + its org. The surface is deliberately minimal:

  - browse the org's open (tendered) loads  — WITHOUT customer rates/margins
  - submit an offer  → lands in the Quote Desk as source='carrier_app'
  - see their own assigned loads (their pay only) + upload POD/BOL paperwork
  - share phone GPS → check-calls feeding the load's tracking map
"""
from datetime import datetime, timezone
from decimal import Decimal

from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, UploadFile, status as http
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session as DbSession

from app import events, offers
from app.database import get_db
from app.models import Carrier, CheckCall, Document, Load, Organization
from app.security import hash_token

router = APIRouter(prefix="/api/portal", tags=["carrier-portal"])

OPEN_STATUSES = ("tendered",)
MY_STATUSES = ("covered", "dispatched", "in_transit", "delivered", "invoiced")
ALLOWED_DOC_KINDS = {"pod", "bol", "other"}
MAX_DOC_BYTES = 15 * 1024 * 1024


def get_portal_carrier(token: str = Query(...), db: DbSession = Depends(get_db)) -> Carrier:
    carrier = (
        db.query(Carrier)
        .filter(Carrier.portal_token_hash == hash_token(token))
        .first()
    )
    if carrier is None:
        raise HTTPException(status_code=http.HTTP_404_NOT_FOUND, detail="Invalid portal link")
    if carrier.status == "deactivated":
        raise HTTPException(status_code=http.HTTP_403_FORBIDDEN,
                            detail="This carrier account is deactivated — contact the broker.")
    return carrier


# ── Carrier-safe load shapes (NEVER include customer_rate / margin / shipper) ──

class PortalLoad(BaseModel):
    id: int
    reference: str | None
    origin_city: str | None
    origin_state: str | None
    dest_city: str | None
    dest_state: str | None
    pickup_date: datetime | None
    delivery_date: datetime | None
    equipment: str | None
    commodity: str | None
    weight: int | None
    total_miles: int | None


class PortalMyLoad(PortalLoad):
    status: str
    carrier_rate: Decimal | None  # the carrier's own pay — never the customer side


class PortalMeta(BaseModel):
    carrier_name: str
    org_name: str
    accent_color: str | None = None


class OfferIn(BaseModel):
    rate: Decimal = Field(gt=0)
    notes: str | None = Field(None, max_length=500)


class PingIn(BaseModel):
    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)
    city: str | None = Field(None, max_length=120)
    state: str | None = Field(None, max_length=2)


def _fields(ld: Load) -> dict:
    return dict(
        id=ld.id, reference=ld.reference, origin_city=ld.origin_city,
        origin_state=ld.origin_state, dest_city=ld.dest_city, dest_state=ld.dest_state,
        pickup_date=ld.pickup_date, delivery_date=ld.delivery_date, equipment=ld.equipment,
        commodity=ld.commodity, weight=ld.weight, total_miles=ld.total_miles,
    )


def _own_load(db: DbSession, carrier: Carrier, load_id: int) -> Load:
    load = (
        db.query(Load)
        .filter(Load.id == load_id, Load.organization_id == carrier.organization_id,
                Load.carrier_id == carrier.id)
        .first()
    )
    if load is None:
        raise HTTPException(status_code=http.HTTP_404_NOT_FOUND, detail="Load not found")
    return load


@router.get("/meta", response_model=PortalMeta)
def portal_meta(carrier: Carrier = Depends(get_portal_carrier), db: DbSession = Depends(get_db)):
    org = db.query(Organization).filter(Organization.id == carrier.organization_id).first()
    return PortalMeta(carrier_name=carrier.name, org_name=org.name if org else "Broker",
                      accent_color=org.accent_color if org else None)


@router.get("/loads/available", response_model=list[PortalLoad])
def available_loads(carrier: Carrier = Depends(get_portal_carrier), db: DbSession = Depends(get_db)):
    """The broker's open board: tendered loads, carrier-safe fields only."""
    loads = (
        db.query(Load)
        .filter(Load.organization_id == carrier.organization_id, Load.status.in_(OPEN_STATUSES))
        .order_by(Load.pickup_date.asc().nulls_last(), Load.id.desc())
        .limit(100)
        .all()
    )
    return [PortalLoad(**_fields(ld)) for ld in loads]


@router.post("/loads/{load_id}/offer", response_model=dict, status_code=http.HTTP_201_CREATED)
def submit_offer(load_id: int, payload: OfferIn,
                 carrier: Carrier = Depends(get_portal_carrier), db: DbSession = Depends(get_db)):
    """Carrier self-serves an offer → appears live in the Quote Desk ('app' badge)."""
    load = (
        db.query(Load)
        .filter(Load.id == load_id, Load.organization_id == carrier.organization_id,
                Load.status.in_(OPEN_STATUSES))
        .first()
    )
    if load is None:
        raise HTTPException(status_code=http.HTTP_404_NOT_FOUND,
                            detail="This load is no longer open for offers.")
    offers.create_option(
        db, carrier.organization_id, load.id, source="carrier_app",
        carrier_id=carrier.id, carrier_name=carrier.name,
        mc_number=carrier.mc_number, dot_number=carrier.dot_number,
        rate=payload.rate, notes=payload.notes,
    )
    db.commit()
    return {"submitted": True}


@router.get("/loads/mine", response_model=list[PortalMyLoad])
def my_loads(carrier: Carrier = Depends(get_portal_carrier), db: DbSession = Depends(get_db)):
    loads = (
        db.query(Load)
        .filter(Load.organization_id == carrier.organization_id,
                Load.carrier_id == carrier.id, Load.status.in_(MY_STATUSES))
        .order_by(Load.pickup_date.asc().nulls_last(), Load.id.desc())
        .limit(100)
        .all()
    )
    return [PortalMyLoad(**_fields(ld), status=ld.status, carrier_rate=ld.carrier_rate)
            for ld in loads]


@router.post("/loads/{load_id}/documents", response_model=dict, status_code=http.HTTP_201_CREATED)
async def upload_document(load_id: int, file: UploadFile = File(...), kind: str = Form("pod"),
                          carrier: Carrier = Depends(get_portal_carrier),
                          db: DbSession = Depends(get_db)):
    """Carrier uploads paperwork (POD/BOL) straight onto their own load."""
    load = _own_load(db, carrier, load_id)
    if kind not in ALLOWED_DOC_KINDS:
        raise HTTPException(status_code=http.HTTP_422_UNPROCESSABLE_ENTITY,
                            detail=f"kind must be one of {', '.join(sorted(ALLOWED_DOC_KINDS))}")
    data = await file.read()
    if not data:
        raise HTTPException(status_code=http.HTTP_422_UNPROCESSABLE_ENTITY, detail="Empty file")
    if len(data) > MAX_DOC_BYTES:
        raise HTTPException(status_code=http.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                            detail="File exceeds 15 MB limit")
    db.add(Document(
        organization_id=carrier.organization_id, load_id=load.id,
        filename=file.filename or "upload", content_type=file.content_type,
        size=len(data), kind=kind, data=data, uploaded_by=None,
    ))
    events.log_event(
        db, org_id=carrier.organization_id, load_id=load.id, event_type="doc_uploaded",
        subject=f"{carrier.name} uploaded {kind.upper()}: {file.filename or 'file'} (carrier app)",
        meta={"kind": kind, "source": "carrier_app"},
    )
    db.commit()
    return {"uploaded": True}


@router.post("/loads/{load_id}/ping", response_model=dict, status_code=http.HTTP_201_CREATED)
def gps_ping(load_id: int, payload: PingIn,
             carrier: Carrier = Depends(get_portal_carrier), db: DbSession = Depends(get_db)):
    """Phone location share → a check-call feeding the load's tracking map."""
    load = _own_load(db, carrier, load_id)
    db.add(CheckCall(
        organization_id=carrier.organization_id, load_id=load.id,
        city=payload.city, state=(payload.state or "").upper() or None,
        latitude=payload.latitude, longitude=payload.longitude,
        status_note="Carrier app GPS", reported_at=datetime.now(timezone.utc),
        created_by=None,
    ))
    db.commit()
    return {"received": True}
