/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_companies_get"];
        put?: never;
        /** Create Company */
        post: operations["create_company_api_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_companies__company_id__get"];
        put?: never;
        post?: never;
        /** Delete Company */
        delete: operations["delete_company_api_companies__company_id__delete"];
        options?: never;
        head?: never;
        /** Update Company */
        patch: operations["update_company_api_companies__company_id__patch"];
        trace?: never;
    };
    "/api/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["list_contacts_api_contacts_get"];
        put?: never;
        /** Create Contact */
        post: operations["create_contact_api_contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contact */
        get: operations["get_contact_api_contacts__contact_id__get"];
        put?: never;
        post?: never;
        /** Delete Contact */
        delete: operations["delete_contact_api_contacts__contact_id__delete"];
        options?: never;
        head?: never;
        /** Update Contact */
        patch: operations["update_contact_api_contacts__contact_id__patch"];
        trace?: never;
    };
    "/api/carriers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Carriers */
        get: operations["list_carriers_api_carriers_get"];
        put?: never;
        /** Create Carrier */
        post: operations["create_carrier_api_carriers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carriers/{carrier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Carrier */
        get: operations["get_carrier_api_carriers__carrier_id__get"];
        put?: never;
        post?: never;
        /** Delete Carrier */
        delete: operations["delete_carrier_api_carriers__carrier_id__delete"];
        options?: never;
        head?: never;
        /** Update Carrier */
        patch: operations["update_carrier_api_carriers__carrier_id__patch"];
        trace?: never;
    };
    "/api/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pipelines */
        get: operations["list_pipelines_api_pipelines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deals */
        get: operations["list_deals_api_deals_get"];
        put?: never;
        /** Create Deal */
        post: operations["create_deal_api_deals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{deal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deal */
        get: operations["get_deal_api_deals__deal_id__get"];
        put?: never;
        post?: never;
        /** Delete Deal */
        delete: operations["delete_deal_api_deals__deal_id__delete"];
        options?: never;
        head?: never;
        /** Update Deal */
        patch: operations["update_deal_api_deals__deal_id__patch"];
        trace?: never;
    };
    "/api/deals/{deal_id}/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change Stage
         * @description Kanban drag target: move a deal to another stage in its pipeline.
         */
        patch: operations["change_stage_api_deals__deal_id__stage_patch"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CarrierCreate */
        CarrierCreate: {
            /** Name */
            name: string;
            /** Mc Number */
            mc_number?: string | null;
            /** Dot Number */
            dot_number?: string | null;
            /** Hq City */
            hq_city?: string | null;
            /** Hq State */
            hq_state?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Rating */
            rating?: number | string | null;
            /** On Time Pct */
            on_time_pct?: number | null;
            /** Tracking Pct */
            tracking_pct?: number | null;
            /** Bounce Pct */
            bounce_pct?: number | null;
            /** Auto Liability */
            auto_liability?: number | string | null;
            /** Cargo Coverage */
            cargo_coverage?: number | string | null;
            /** Equipment Types */
            equipment_types?: string | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** CarrierOut */
        CarrierOut: {
            /** Name */
            name: string;
            /** Mc Number */
            mc_number?: string | null;
            /** Dot Number */
            dot_number?: string | null;
            /** Hq City */
            hq_city?: string | null;
            /** Hq State */
            hq_state?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Rating */
            rating?: string | null;
            /** On Time Pct */
            on_time_pct?: number | null;
            /** Tracking Pct */
            tracking_pct?: number | null;
            /** Bounce Pct */
            bounce_pct?: number | null;
            /** Auto Liability */
            auto_liability?: string | null;
            /** Cargo Coverage */
            cargo_coverage?: string | null;
            /** Equipment Types */
            equipment_types?: string | null;
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Owner Id */
            owner_id: number | null;
            /** Created By */
            created_by: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CarrierUpdate */
        CarrierUpdate: {
            /** Name */
            name?: string | null;
            /** Mc Number */
            mc_number?: string | null;
            /** Dot Number */
            dot_number?: string | null;
            /** Hq City */
            hq_city?: string | null;
            /** Hq State */
            hq_state?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Status */
            status?: string | null;
            /** Rating */
            rating?: number | string | null;
            /** On Time Pct */
            on_time_pct?: number | null;
            /** Tracking Pct */
            tracking_pct?: number | null;
            /** Bounce Pct */
            bounce_pct?: number | null;
            /** Auto Liability */
            auto_liability?: number | string | null;
            /** Cargo Coverage */
            cargo_coverage?: number | string | null;
            /** Equipment Types */
            equipment_types?: string | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** CompanyCreate */
        CompanyCreate: {
            /** Name */
            name: string;
            /** Domain */
            domain?: string | null;
            /** Industry */
            industry?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** CompanyOut */
        CompanyOut: {
            /** Name */
            name: string;
            /** Domain */
            domain?: string | null;
            /** Industry */
            industry?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Owner Id */
            owner_id: number | null;
            /** Created By */
            created_by: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CompanyUpdate */
        CompanyUpdate: {
            /** Name */
            name?: string | null;
            /** Domain */
            domain?: string | null;
            /** Industry */
            industry?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** ContactCreate */
        ContactCreate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Title */
            title?: string | null;
            /** Company Id */
            company_id?: number | null;
            /** Carrier Id */
            carrier_id?: number | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** ContactOut */
        ContactOut: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Title */
            title?: string | null;
            /** Company Id */
            company_id?: number | null;
            /** Carrier Id */
            carrier_id?: number | null;
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Owner Id */
            owner_id: number | null;
            /** Created By */
            created_by: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            company?: components["schemas"]["app__schemas__contact__ContactRef"] | null;
            carrier?: components["schemas"]["app__schemas__contact__ContactRef"] | null;
        };
        /** ContactUpdate */
        ContactUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Title */
            title?: string | null;
            /** Company Id */
            company_id?: number | null;
            /** Carrier Id */
            carrier_id?: number | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** DealCreate */
        DealCreate: {
            /** Name */
            name: string;
            /** Amount */
            amount?: number | string | null;
            /** Company Id */
            company_id?: number | null;
            /** Primary Contact Id */
            primary_contact_id?: number | null;
            /** Expected Close Date */
            expected_close_date?: string | null;
            /** Pipeline Id */
            pipeline_id?: number | null;
            /** Stage Id */
            stage_id?: number | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** DealOut */
        DealOut: {
            /** Name */
            name: string;
            /** Amount */
            amount?: string | null;
            /** Company Id */
            company_id?: number | null;
            /** Primary Contact Id */
            primary_contact_id?: number | null;
            /** Expected Close Date */
            expected_close_date?: string | null;
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Pipeline Id */
            pipeline_id: number;
            /** Stage Id */
            stage_id: number;
            /** Owner Id */
            owner_id: number | null;
            /** Created By */
            created_by: number | null;
            /** Closed At */
            closed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            company?: components["schemas"]["DealRef"] | null;
            primary_contact?: components["schemas"]["app__schemas__deal__ContactRef"] | null;
        };
        /**
         * DealRef
         * @description Lightweight linked-record summary embedded on a deal.
         */
        DealRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * DealStageUpdate
         * @description Body for the kanban drag → stage-change endpoint.
         */
        DealStageUpdate: {
            /** Stage Id */
            stage_id: number;
        };
        /** DealUpdate */
        DealUpdate: {
            /** Name */
            name?: string | null;
            /** Amount */
            amount?: number | string | null;
            /** Company Id */
            company_id?: number | null;
            /** Primary Contact Id */
            primary_contact_id?: number | null;
            /** Expected Close Date */
            expected_close_date?: string | null;
            /** Stage Id */
            stage_id?: number | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            organization: components["schemas"]["OrganizationOut"];
        };
        /** OrganizationOut */
        OrganizationOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Plan */
            plan: string;
        };
        /** Page[CarrierOut] */
        Page_CarrierOut_: {
            /** Items */
            items: components["schemas"]["CarrierOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[CompanyOut] */
        Page_CompanyOut_: {
            /** Items */
            items: components["schemas"]["CompanyOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[ContactOut] */
        Page_ContactOut_: {
            /** Items */
            items: components["schemas"]["ContactOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[DealOut] */
        Page_DealOut_: {
            /** Items */
            items: components["schemas"]["DealOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PipelineOut */
        PipelineOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Is Default */
            is_default: boolean;
            /** Stages */
            stages: components["schemas"]["StageOut"][];
        };
        /** StageOut */
        StageOut: {
            /** Id */
            id: number;
            /** Pipeline Id */
            pipeline_id: number;
            /** Name */
            name: string;
            /** Sort Order */
            sort_order: number;
            /** Is Won */
            is_won: boolean;
            /** Is Lost */
            is_lost: boolean;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Organization Id */
            organization_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ContactRef
         * @description Lightweight linked-account summary embedded in a contact.
         */
        app__schemas__contact__ContactRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ContactRef */
        app__schemas__deal__ContactRef: {
            /** Id */
            id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    list_companies_api_companies_get: {
        parameters: {
            query?: {
                search?: string | null;
                owner_id?: number | null;
                industry?: string | null;
                sort?: string;
                order?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CompanyOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_api_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_company_api_companies__company_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company_api_companies__company_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contacts_api_contacts_get: {
        parameters: {
            query?: {
                search?: string | null;
                owner_id?: number | null;
                company_id?: number | null;
                carrier_id?: number | null;
                sort?: string;
                order?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ContactOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contact_api_contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contact_api_contacts__contact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contact_api_contacts__contact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contact_api_contacts__contact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_carriers_api_carriers_get: {
        parameters: {
            query?: {
                search?: string | null;
                owner_id?: number | null;
                status?: string | null;
                sort?: string;
                order?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CarrierOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_carrier_api_carriers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarrierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_carrier_api_carriers__carrier_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carrier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_carrier_api_carriers__carrier_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carrier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_carrier_api_carriers__carrier_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carrier_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarrierUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pipelines_api_pipelines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineOut"][];
                };
            };
        };
    };
    list_deals_api_deals_get: {
        parameters: {
            query?: {
                search?: string | null;
                pipeline_id?: number | null;
                stage_id?: number | null;
                owner_id?: number | null;
                sort?: string;
                order?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DealOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deal_api_deals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deal_api_deals__deal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deal_api_deals__deal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deal_api_deals__deal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_stage_api_deals__deal_id__stage_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealStageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
