"""carrier portal token

Revision ID: 22f165fcba64
Revises: a38a2655414a
Create Date: 2026-07-07 14:05:57.455961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f165fcba64'
down_revision: Union[str, Sequence[str], None] = 'a38a2655414a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carriers', sa.Column('portal_token_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_carriers_portal_token_hash'), 'carriers', ['portal_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carriers_portal_token_hash'), table_name='carriers')
    op.drop_column('carriers', 'portal_token_hash')
    # ### end Alembic commands ###
