"""freight F1: carriers table + contacts.carrier_id

Revision ID: 275491d1d606
Revises: e044fdfd8210
Create Date: 2026-06-30 00:19:34.158526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275491d1d606'
down_revision: Union[str, Sequence[str], None] = 'e044fdfd8210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mc_number', sa.String(length=50), nullable=True),
    sa.Column('dot_number', sa.String(length=50), nullable=True),
    sa.Column('hq_city', sa.String(length=120), nullable=True),
    sa.Column('hq_state', sa.String(length=2), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('on_time_pct', sa.Integer(), nullable=True),
    sa.Column('tracking_pct', sa.Integer(), nullable=True),
    sa.Column('bounce_pct', sa.Integer(), nullable=True),
    sa.Column('auto_liability', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cargo_coverage', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('equipment_types', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carriers_organization_id'), 'carriers', ['organization_id'], unique=False)
    # Batch mode so SQLite can add the FK column (copy-and-move strategy).
    with op.batch_alter_table('contacts') as batch_op:
        batch_op.add_column(sa.Column('carrier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_contacts_carrier_id', 'carriers', ['carrier_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts') as batch_op:
        batch_op.drop_constraint('fk_contacts_carrier_id', type_='foreignkey')
        batch_op.drop_column('carrier_id')
    op.drop_index(op.f('ix_carriers_organization_id'), table_name='carriers')
    op.drop_table('carriers')
    # ### end Alembic commands ###
