"""feed events + mentions

Revision ID: 55c4f7ce4243
Revises: 22f165fcba64
Create Date: 2026-07-08 08:59:13.030543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c4f7ce4243'
down_revision: Union[str, Sequence[str], None] = '22f165fcba64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('kind', sa.String(length=10), server_default='user', nullable=False))
    op.add_column('activities', sa.Column('event_type', sa.String(length=40), nullable=True))
    op.add_column('activities', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('activities', sa.Column('mentions', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('mentions_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mentions_seen_at')
    op.drop_column('activities', 'mentions')
    op.drop_column('activities', 'meta')
    op.drop_column('activities', 'event_type')
    op.drop_column('activities', 'kind')
    # ### end Alembic commands ###
