"""options page: option MC/source, offered lock, rate confirmations

Revision ID: 8997a3f593b6
Revises: 90ba38485c98
Create Date: 2026-07-07 02:49:41.148840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8997a3f593b6'
down_revision: Union[str, Sequence[str], None] = '90ba38485c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('doc_hash', sa.String(length=64), nullable=False),
    sa.Column('sent_to', sa.String(length=320), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signer_name', sa.String(length=255), nullable=True),
    sa.Column('signer_ip', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['load_options.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_confirmations_load_id'), 'rate_confirmations', ['load_id'], unique=False)
    op.create_index(op.f('ix_rate_confirmations_organization_id'), 'rate_confirmations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rate_confirmations_token_hash'), 'rate_confirmations', ['token_hash'], unique=False)
    op.add_column('load_options', sa.Column('mc_number', sa.String(length=50), nullable=True))
    op.add_column('load_options', sa.Column('dot_number', sa.String(length=50), nullable=True))
    # server_default backfills existing rows; matches the model default.
    op.add_column('load_options', sa.Column('source', sa.String(length=20), nullable=False,
                                            server_default='manual'))
    # Batch mode: SQLite can't ALTER-add an FK in place (copy-and-move instead).
    with op.batch_alter_table('loads') as batch:
        batch.add_column(sa.Column('offered_carrier_id', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('offer_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch.create_foreign_key('fk_loads_offered_carrier', 'carriers',
                                 ['offered_carrier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loads') as batch:
        batch.drop_constraint('fk_loads_offered_carrier', type_='foreignkey')
        batch.drop_column('offer_expires_at')
        batch.drop_column('offered_carrier_id')
    op.drop_column('load_options', 'source')
    op.drop_column('load_options', 'dot_number')
    op.drop_column('load_options', 'mc_number')
    op.drop_index(op.f('ix_rate_confirmations_token_hash'), table_name='rate_confirmations')
    op.drop_index(op.f('ix_rate_confirmations_organization_id'), table_name='rate_confirmations')
    op.drop_index(op.f('ix_rate_confirmations_load_id'), table_name='rate_confirmations')
    op.drop_table('rate_confirmations')
    # ### end Alembic commands ###
