"""loads: DAT posting fields

Revision ID: 995b3397c785
Revises: b6a843d1d456
Create Date: 2026-07-01 13:22:51.028345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995b3397c785'
down_revision: Union[str, Sequence[str], None] = 'b6a843d1d456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loads', sa.Column('dat_posting_id', sa.String(length=80), nullable=True))
    op.add_column('loads', sa.Column('dat_posted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loads', 'dat_posted_at')
    op.drop_column('loads', 'dat_posting_id')
    # ### end Alembic commands ###
