"""F2: loads table

Revision ID: a1196e601f28
Revises: d0105b350651
Create Date: 2026-06-30 00:52:15.649780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1196e601f28'
down_revision: Union[str, Sequence[str], None] = 'd0105b350651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('shipper_id', sa.Integer(), nullable=True),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('primary_contact_id', sa.Integer(), nullable=True),
    sa.Column('commodity', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.String(length=80), nullable=True),
    sa.Column('origin_city', sa.String(length=120), nullable=True),
    sa.Column('origin_state', sa.String(length=2), nullable=True),
    sa.Column('dest_city', sa.String(length=120), nullable=True),
    sa.Column('dest_state', sa.String(length=2), nullable=True),
    sa.Column('pickup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_miles', sa.Integer(), nullable=True),
    sa.Column('customer_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('carrier_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['primary_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['shipper_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loads_organization_id'), 'loads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_loads_reference'), 'loads', ['reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loads_reference'), table_name='loads')
    op.drop_index(op.f('ix_loads_organization_id'), table_name='loads')
    op.drop_table('loads')
    # ### end Alembic commands ###
