"""sales coverage: users.sales_code + companies.secondary_owner_id

Revision ID: a38a2655414a
Revises: 8997a3f593b6
Create Date: 2026-07-07 12:43:44.622207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38a2655414a'
down_revision: Union[str, Sequence[str], None] = '8997a3f593b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Batch mode: SQLite can't ALTER-add an FK in place.
    with op.batch_alter_table('companies') as batch:
        batch.add_column(sa.Column('secondary_owner_id', sa.Integer(), nullable=True))
        batch.create_foreign_key('fk_companies_secondary_owner', 'users',
                                 ['secondary_owner_id'], ['id'])
    op.add_column('users', sa.Column('sales_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sales_code')
    with op.batch_alter_table('companies') as batch:
        batch.drop_constraint('fk_companies_secondary_owner', type_='foreignkey')
        batch.drop_column('secondary_owner_id')
    # ### end Alembic commands ###
