"""F4: activities related_load_id + related_carrier_id

Revision ID: ae924513303f
Revises: d6fc5e3bb161
Create Date: 2026-06-30 17:06:36.366245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae924513303f'
down_revision: Union[str, Sequence[str], None] = 'd6fc5e3bb161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Batch mode so SQLite can add the FK columns (copy-and-move strategy).
    with op.batch_alter_table('activities') as batch_op:
        batch_op.add_column(sa.Column('related_load_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('related_carrier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_activities_related_carrier_id', 'carriers', ['related_carrier_id'], ['id'])
        batch_op.create_foreign_key('fk_activities_related_load_id', 'loads', ['related_load_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities') as batch_op:
        batch_op.drop_constraint('fk_activities_related_carrier_id', type_='foreignkey')
        batch_op.drop_constraint('fk_activities_related_load_id', type_='foreignkey')
        batch_op.drop_column('related_carrier_id')
        batch_op.drop_column('related_load_id')
    # ### end Alembic commands ###
