"""carrier vetting snapshots

Revision ID: b6a843d1d456
Revises: 8f8f1f882eee
Create Date: 2026-06-30 23:17:33.332246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a843d1d456'
down_revision: Union[str, Sequence[str], None] = '8f8f1f882eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_vettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('authority_status', sa.String(length=20), nullable=True),
    sa.Column('insurance_on_file', sa.Boolean(), nullable=False),
    sa.Column('safety_rating', sa.String(length=40), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('checked_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_vettings_carrier_id'), 'carrier_vettings', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_carrier_vettings_organization_id'), 'carrier_vettings', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carrier_vettings_organization_id'), table_name='carrier_vettings')
    op.drop_index(op.f('ix_carrier_vettings_carrier_id'), table_name='carrier_vettings')
    op.drop_table('carrier_vettings')
    # ### end Alembic commands ###
