"""per-tenant branding: organizations.accent_color + logo_url

Revision ID: d0105b350651
Revises: 275491d1d606
Create Date: 2026-06-30 00:43:06.812999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0105b350651'
down_revision: Union[str, Sequence[str], None] = '275491d1d606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('accent_color', sa.String(length=9), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'accent_color')
    # ### end Alembic commands ###
