"""F3: carrier_capacity

Revision ID: d6fc5e3bb161
Revises: 91b594e52056
Create Date: 2026-06-30 16:37:00.904882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fc5e3bb161'
down_revision: Union[str, Sequence[str], None] = '91b594e52056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_capacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('radius_miles', sa.Integer(), nullable=True),
    sa.Column('weekly_capacity', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_capacity_carrier_id'), 'carrier_capacity', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_carrier_capacity_organization_id'), 'carrier_capacity', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carrier_capacity_organization_id'), table_name='carrier_capacity')
    op.drop_index(op.f('ix_carrier_capacity_carrier_id'), table_name='carrier_capacity')
    op.drop_table('carrier_capacity')
    # ### end Alembic commands ###
