"""S1: load_options + loads.target_rate

Revision ID: d9f127b2bca1
Revises: 9adac6a6f15f
Create Date: 2026-06-30 01:14:35.377267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f127b2bca1'
down_revision: Union[str, Sequence[str], None] = '9adac6a6f15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('carrier_name', sa.String(length=255), nullable=True),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('counter_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_load_options_load_id'), 'load_options', ['load_id'], unique=False)
    op.create_index(op.f('ix_load_options_organization_id'), 'load_options', ['organization_id'], unique=False)
    op.add_column('loads', sa.Column('target_rate', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loads', 'target_rate')
    op.drop_index(op.f('ix_load_options_organization_id'), table_name='load_options')
    op.drop_index(op.f('ix_load_options_load_id'), table_name='load_options')
    op.drop_table('load_options')
    # ### end Alembic commands ###
